name: lephyjepa
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.0.0
  - torchvision
  - cudatoolkit=11.8
  - numpy
  - matplotlib
  - pandas
  - tqdm
  - pillow
  - scikit-learn
  - pyyaml
  - jupyter
  - pip
  - pip:
    - -r requirements.txt
